config/routes.rb
Rails.application.routes.draw do
  root :to => "landing#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :users do
    resources :images
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :images
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # attr_accessible :email, :password, :password_confirmation, :remember_me
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :avatar) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :avatar) }
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
    @user = User.find(params[:user_id])
  end

  def new
    @image = Image.new
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @image = @user.images.new(image_params)
    if @image.save
      redirect_to user_images_path(current_user)
    else
      render :new
    end
  end

  private
  def image_params
    params.require(:image).permit(:title, :url, :photo)
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = current_user
    @user = User.find(params[:id])
    @image = Image.all
  end

  private
  def user_params
    params.require(:user).permit(:photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/index.html.erb
<h1>Images</h1>

<h2><% @user.images.each do |image| %>
    <h2> <%= image_tag image.photo %></h2>
    <% end %>
</h2>

<%= link_to "New Image", new_user_image_path %>
<%= image_tag current_user.images %>

app/views/images/new.html.erb
  <div class="form-group">
    <%= form_for [@user, @image] do |f| %>
    <%= f.label :photo, class: 'col-sm-2 control-label'  %>
    <div class="col-sm-6">
        <%= f.file_field :photo %>
    </div>

    <div class="actions">
      <%= f.submit "OK" %>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">


<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <div class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></div>
  <%= link_to 'Edit profile', edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete %> |
  <%= link_to "Visit Account", user_path(current_user) %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %> |
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flickr2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body>
<div class="container">
  <h1>Flicka</h1>
  <%= render 'layouts/navbar' %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</div>
<hr>
</body>
</html>

app/views/users/show.html.erb
<%= link_to "Add Image", new_user_image_path(current_user) %>